"""
geo_data.py — Listados de estados y ciudades para mejorar la precisión del OCR.
"""

ESTADOS_VENEZUELA = [
    "Amazonas",
    "Anzoátegui",
    "Apure",
    "Aragua",
    "Barinas",
    "Bolívar",
    "Carabobo",
    "Cojedes",
    "Delta Amacuro",
    "Distrito Capital",
    "Falcón",
    "Guárico",
    "Lara",
    "La Guaira",
    "Mérida",
    "Miranda",
    "Monagas",
    "Nueva Esparta",
    "Portuguesa",
    "Sucre",
    "Táchira",
    "Trujillo",
    "Yaracuy",
    "Zulia"
]

CIUDADES_VENEZUELA = [
    "Puerto Ayacucho",
    "Barcelona",
    "San Fernando de Apure",
    "Maracay",
    "Barinas",
    "Ciudad Bolívar",
    "Valencia",
    "San Carlos",
    "Tucupita",
    "Caracas",
    "Coro",
    "San Juan de los Morros",
    "Barquisimeto",
    "La Guaira",
    "Mérida",
    "Los Teques",
    "Maturín",
    "La Asunción",
    "Guanare",
    "Cumaná",
    "San Cristóbal",
    "Trujillo",
    "San Felipe",
    "Maracaibo",
    "San Fernando de Atabapo",
    "Puerto La Cruz",
    "Guasdualito",
    "La Victoria",
    "Socopó",
    "Ciudad Guayana",
    "Puerto Ordaz",
    "San Félix",
    "Puerto Cabello",
    "Tinaquillo",
    "Pedernales",
    "Punto Fijo",
    "Valle de la Pascua",
    "Calabozo",
    "Carora",
    "Catia La Mar",
    "El Vigía",
    "Guarenas",
    "Punta de Mata",
    "Porlamar",
    "Acarigua",
    "Carúpano",
    "Táriba",
    "Valera",
    "Chivacoa",
    "Cabimas",
    "Isla Ratón",
    "El Tigre",
    "Biruaca",
    "Turmero",
    "Barinitas",
    "Upata",
    "Guacara",
    "El Pao",
    "Curiapo",
    "Churuguara",
    "Cabudare",
    "Maiquetía",
    "Tovar",
    "Guatire",
    "Caripe",
    "Juan Griego",
    "Araure",
    "Güiria",
    "San Antonio del Táchira",
    "Boconó",
    "Nirgua",
    "Ciudad Ojeda",
    "Anaco",
    "Elorza",
    "Cagua",
    "Santa Bárbara",
    "Tucacas",
    "Zaraza",
    "El Tocuyo",
    "Macuto",
    "Ejido",
    "Santa Teresa del Tuy",
    "Pampatar",
    "Turén",
    "Cumanacoa",
    "La Grita",
    "La Puerta",
    "Yaritagua",
    "San Francisco",
    "Lechería",
    "El Limón",
    "San Diego",
    "Naguanagua",
    "Petare",
    "Machiques",
    "Tocuyito"
]
